# Generated by Django 5.2.12 on 2026-03-18 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('assignee', models.CharField(blank=True, choices=[('', 'Unassigned'), ('sarah', 'Sarah'), ('marcus', 'Marcus')], default='', max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlook_id', models.CharField(max_length=500, unique=True)),
                ('conversation_id', models.CharField(db_index=True, max_length=500)),
                ('subject', models.CharField(max_length=500)),
                ('sender', models.CharField(max_length=255)),
                ('received_at', models.DateTimeField()),
                ('body_preview', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
