# Generated by Django 5.2.12 on 2026-03-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='todo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assignee',
            field=models.CharField(blank=True, choices=[('', 'Me'), ('ma', 'MA'), ('tb', 'TB')], default='', max_length=50),
        ),
    ]
