# Generated by Django 5.2.12 on 2026-03-19 04:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_due_date_ticket_todo_alter_ticket_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='', max_length=10),
        ),
        migrations.CreateModel(
            name='WaitingOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=500)),
                ('from_who', models.CharField(blank=True, max_length=255)),
                ('asked_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_on', to='tickets.ticket')),
            ],
            options={
                'ordering': ['resolved', 'asked_date'],
            },
        ),
    ]
