# Generated by Django 5.2.12 on 2026-03-19 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_priority_waitingon'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingon',
            name='thread_email',
            field=models.ForeignKey(blank=True, help_text='Latest email of the linked thread', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiting_on_items', to='tickets.ticketemail'),
        ),
    ]
