# Generated by Django 5.2.12 on 2026-03-19 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_waitingon_thread_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='todo',
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=500)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread_email', models.ForeignKey(blank=True, help_text='Latest email of the linked thread', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='tickets.ticketemail')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='tickets.ticket')),
            ],
            options={
                'ordering': ['done', 'due_date', 'created_at'],
            },
        ),
    ]
