# Generated by Django 5.2.12 on 2026-03-19 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_ticket_due_date_remove_ticket_todo_todoitem'),
    ]

    operations = [
        # 1. Create the Assignee model
        migrations.CreateModel(
            name='Assignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        # 2. Add assignee FK to TodoItem (nullable — no data issue)
        migrations.AddField(
            model_name='todoitem',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='tickets.assignee'),
        ),
        # 3. Add NEW nullable FK alongside old CharField on Ticket
        migrations.AddField(
            model_name='ticket',
            name='assignee_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.assignee'),
        ),
        # 4. Drop the old VARCHAR assignee column
        migrations.RemoveField(
            model_name='ticket',
            name='assignee',
        ),
        # 5. Rename the new FK to 'assignee'
        migrations.RenameField(
            model_name='ticket',
            old_name='assignee_fk',
            new_name='assignee',
        ),
    ]
