# Generated by Django 5.2.12 on 2026-03-21 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_migrate_status_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='waiting_on',
            field=models.ForeignKey(blank=True, help_text='Blocked until this waiting-on item is resolved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_todos', to='tickets.waitingon'),
        ),
    ]
