# Generated by Django 5.2.12 on 2026-03-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_todo_waiting_on_dependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketemail',
            name='is_seed',
            field=models.BooleanField(default=False),
        ),
    ]
