# Generated by Django 5.2.12 on 2026-03-22 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_add_ticketemail_is_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_notes', to='tickets.ticket')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('ticket', 'author_email', 'created_at')},
            },
        ),
    ]
